import Foundation

public enum MigrationSchemaReplay {
    /// Refuses a single file larger than this rather than pulling an arbitrary
    /// blob that happens to carry a `.sql` suffix into memory.
    static let maximumFileBytes = 16 * 1024 * 1024

    public struct Progress: Sendable, Hashable {
        public let completedFiles: Int
        public let totalFiles: Int
        public let fileName: String
    }

    /// Replays `files` in order and returns the schema they describe.
    public static func buildModel(
        files: [MigrationFile],
        dialect: SQLDialect,
        progress: @Sendable (Progress) -> Void = { _ in }
    ) throws -> MigrationSchemaModel {
        let builder = MigrationSchemaBuilder(dialect: dialect)
        var readFailures: [MigrationDiagnostic] = []

        for (offset, file) in files.enumerated() {
            try Task.checkCancellation()
            progress(Progress(completedFiles: offset, totalFiles: files.count, fileName: file.fileName))
            do {
                builder.apply(sql: try read(file.url), fileName: file.fileName)
            } catch {
                readFailures.append(
                    MigrationDiagnostic(fileName: file.fileName,
                                        message: "could not be read: \(error.localizedDescription)",
                                        statementPreview: "")
                )
            }
        }
        progress(Progress(completedFiles: files.count, totalFiles: files.count, fileName: ""))

        let model = builder.makeModel(fileCount: files.count)
        guard !readFailures.isEmpty else { return model }
        return MigrationSchemaModel(
            catalog: model.catalog,
            diagnostics: readFailures + model.diagnostics,
            fileCount: model.fileCount,
            statementCount: model.statementCount,
            dialect: model.dialect
        )
    }

    /// Enough of a file to recognise dialect markers. Reading whole files just
    /// to guess a dialect made discovery cost seconds per large SQL dump.
    static let dialectSampleBytes = 64 * 1024

    static func read(_ url: URL, limit: Int? = nil) throws -> String {
        if let limit {
            // Read a bounded prefix rather than mapping the file: `.mappedIfSafe`
            // falls back to a whole-file read on volumes it will not map, such as
            // a network share, which would defeat the point of sampling.
            guard let handle = try? FileHandle(forReadingFrom: url) else {
                throw DatabaseUserError(kind: .notFound, message: "the file could not be opened")
            }
            defer { try? handle.close() }
            let sample = (try handle.read(upToCount: limit)) ?? Data()
            // A cut multi-byte character only costs a replacement character in
            // text this is about to scan for markers.
            return String(decoding: sample, as: UTF8.self)
        }
        // A size that cannot be read is treated as too large rather than as
        // zero, so a file the scan cannot measure is never pulled in whole.
        let size = (try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize) ?? Int.max
        guard size <= maximumFileBytes else {
            throw DatabaseUserError(kind: .invalidInput,
                                    message: "the file is larger than \(maximumFileBytes / (1024 * 1024)) MB")
        }
        let data = try Data(contentsOf: url, options: [.mappedIfSafe])
        if let text = String(data: data, encoding: .utf8) { return text }
        // A migration written in a legacy single-byte encoding still parses; only
        // literal text loses fidelity, and this model never evaluates literals.
        return String(decoding: data, as: UTF8.self)
    }

    private static let sqliteMarkers = ["autoincrement", "without rowid", "pragma ", "sqlite_"]
    private static let postgresMarkers = [
        "jsonb", "timestamptz", "bigserial", "serial", "::", "$$", "create extension",
        "gen_random_uuid", "text[]", "uuid", "now()", "citext", "tsvector", "generated by default as identity",
    ]

    /// Picks a dialect from the directory path and the text of a sample of the
    /// files. PostgreSQL is the default because it is the only dialect with
    /// syntax this parser must treat specially.
    public static func detectDialect(directoryURL: URL, files: [MigrationFile]) -> SQLDialect {
        let path = directoryURL.path.lowercased()
        if path.contains("sqlite") { return .sqlite }
        if path.contains("postgres") || path.contains("pgsql") { return .postgreSQL }

        var sqliteScore = 0
        var postgresScore = 0
        for file in sample(files) {
            guard let text = try? read(file.url, limit: dialectSampleBytes) else { continue }
            let lowercased = text.lowercased()
            for marker in sqliteMarkers where lowercased.contains(marker) { sqliteScore += 1 }
            for marker in postgresMarkers where lowercased.contains(marker) { postgresScore += 1 }
        }
        return sqliteScore > postgresScore ? .sqlite : .postgreSQL
    }

    private static func sample(_ files: [MigrationFile]) -> [MigrationFile] {
        guard files.count > 6 else { return files }
        return Array(files.prefix(3)) + Array(files.suffix(3))
    }
}
