#!/usr/bin/env python3
"""Embed canonical Skills/*/SKILL.md text in the Swift application target."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


SKILLS = {
    "graph-clusters": "graphClustersContent",
    "schema-descriptions": "schemaDescriptionsContent",
    "database-explore": "databaseExploreContent",
    "database-diff": "databaseDiffContent",
    "database-preview": "databasePreviewContent",
}


def generated_source(repository: Path) -> str:
    lines = [
        "// Generated by Tools/generate_embedded_skills.py from Skills/*/SKILL.md.",
        "// Edit the canonical skill and run the generator; do not edit this file.",
        "extension StudioSkills {",
    ]
    for skill_id, symbol in SKILLS.items():
        content = (repository / "Skills" / skill_id / "SKILL.md").read_text(encoding="utf-8")
        if '"""#' in content:
            raise ValueError(f"{skill_id} contains the raw-string terminator")
        lines.extend((f"    static let {symbol} = #\"\"\"",))
        lines.extend("    " + line if line else "" for line in content.rstrip("\n").split("\n"))
        lines.extend(("    \"\"\"#", ""))
    known = json.loads((repository / "Tools" / "known_managed_skills.json").read_text(encoding="utf-8"))
    lines.append("    static let knownManagedHashes: [String: Set<String>] = [")
    for skill_id, hashes in sorted(known.items()):
        if not all(len(value) == 64 and all(character in "0123456789abcdef" for character in value) for value in hashes):
            raise ValueError(f"Invalid managed skill hash for {skill_id}")
        values = ", ".join(f'"{value}"' for value in hashes)
        lines.append(f'        "{skill_id}": [{values}],')
    lines.append("    ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def generated_mcp_catalog(repository: Path) -> str:
    """Bundle canonical user-wide skills and hashes used to recognize old managed copies."""
    known = json.loads((repository / "Tools" / "known_managed_skills.json").read_text(encoding="utf-8"))
    skills = []
    for skill_id in SKILLS:
        content = (repository / "Skills" / skill_id / "SKILL.md").read_text(encoding="utf-8")
        hashes = list(known.get(skill_id, []))
        current_hash = hashlib.sha256(content.encode("utf-8")).hexdigest()
        if current_hash not in hashes:
            hashes.append(current_hash)
        skills.append({"id": skill_id, "content": content, "managed_sha256": hashes})
    retired = []
    for skill_id in sorted(set(known) - set(SKILLS)):
        retired.append({"id": skill_id, "managed_sha256": known[skill_id]})
    catalog = {"version": 1, "skills": skills, "retired_skills": retired}
    return json.dumps(catalog, indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated Swift is stale")
    options = parser.parse_args()
    repository = Path(__file__).resolve().parents[1]
    destination = repository / "Sources" / "StudioCore" / "App" / "GeneratedStudioSkillContents.swift"
    content = generated_source(repository)
    mcp_destination = repository / "Sources" / "StudioMCP" / "Resources" / "CanonicalSkills.json"
    mcp_content = generated_mcp_catalog(repository)
    if options.check:
        stale = []
        if not destination.exists() or destination.read_text(encoding="utf-8") != content:
            stale.append(str(destination))
        if not mcp_destination.exists() or mcp_destination.read_text(encoding="utf-8") != mcp_content:
            stale.append(str(mcp_destination))
        if stale:
            raise SystemExit("Stale generated skill resources:\n" + "\n".join(stale))
        print("Embedded and MCP skill contents match canonical sources.")
    else:
        destination.write_text(content, encoding="utf-8")
        mcp_destination.write_text(mcp_content, encoding="utf-8")
        print(f"Generated {destination}")
        print(f"Generated {mcp_destination}")


if __name__ == "__main__":
    main()
