@preconcurrency import GRDB
import CryptoKit
import Foundation

public enum SQLiteObjectType: String, Sendable, Hashable, CaseIterable {
    case table
    case partitionedTable
    case view
    case materializedView
    case virtual
    case shadow
    case unknown

    init(rawDatabaseType: String) {
        switch rawDatabaseType.lowercased() {
        case "table":
            self = .table
        case "partitioned table", "partitionedtable":
            self = .partitionedTable
        case "view":
            self = .view
        case "materialized view", "materializedview":
            self = .materializedView
        case "virtual":
            self = .virtual
        case "shadow":
            self = .shadow
        default:
            self = .unknown
        }
    }
}

/// Neutral object-type name retained alongside the historical SQLite name.
public typealias DatabaseObjectType = SQLiteObjectType

public enum ColumnAffinity: String, Sendable, Hashable, CaseIterable {
    case integer
    case real
    case text
    case blob
    case numeric
    case none

    init(declaredType: String) {
        let uppercased = declaredType.uppercased()
        if uppercased.contains("INT") {
            self = .integer
        } else if uppercased.contains("CHAR") || uppercased.contains("CLOB") || uppercased.contains("TEXT") {
            self = .text
        } else if uppercased.contains("BLOB") {
            self = .blob
        } else if uppercased.contains("REAL") || uppercased.contains("FLOA") || uppercased.contains("DOUB") {
            self = .real
        } else if uppercased.isEmpty {
            self = .none
        } else {
            self = .numeric
        }
    }
}

public enum SortDirection: String, Sendable, Hashable {
    case ascending
    case descending

    var sqlKeyword: String {
        switch self {
        case .ascending:
            return "ASC"
        case .descending:
            return "DESC"
        }
    }

    var toggled: SortDirection {
        switch self {
        case .ascending:
            return .descending
        case .descending:
            return .ascending
        }
    }
}

public enum RowIdentityStrategy: String, Sendable, Hashable {
    case primaryKey
    case rowID
    case readOnly
}

public struct TableColumn: Identifiable, Sendable, Hashable {
    public let id: String
    public let name: String
    public let declaredType: String
    public let notNull: Bool
    public let defaultValueSQL: String?
    public let primaryKeyOrdinal: Int
    public let hiddenValue: Int
    public let identityKind: String
    /// PostgreSQL descriptors set this to false. SQLite keeps the historical
    /// affinity-based editability behavior when it is nil.
    public let editabilityOverride: Bool?

    public init(
        name: String,
        declaredType: String,
        notNull: Bool,
        defaultValueSQL: String?,
        primaryKeyOrdinal: Int,
        hiddenValue: Int,
        isEditable: Bool? = nil,
        identityKind: String = ""
    ) {
        self.id = name
        self.name = name
        self.declaredType = declaredType
        self.notNull = notNull
        self.defaultValueSQL = defaultValueSQL
        self.primaryKeyOrdinal = primaryKeyOrdinal
        self.hiddenValue = hiddenValue
        self.identityKind = identityKind
        self.editabilityOverride = isEditable
    }

    public var affinity: ColumnAffinity {
        ColumnAffinity(declaredType: declaredType)
    }

    public var isGenerated: Bool {
        hiddenValue != 0
    }

    public var isIdentity: Bool {
        !identityKind.isEmpty
    }

    public var identityLabel: String? {
        switch identityKind {
        case "a":
            return "GENERATED ALWAYS AS IDENTITY"
        case "d":
            return "GENERATED BY DEFAULT AS IDENTITY"
        default:
            return identityKind.isEmpty ? nil : "IDENTITY"
        }
    }

    public var isEditable: Bool {
        (editabilityOverride ?? true) && !isGenerated && affinity != .blob
    }

    public var typeLabel: String {
        declaredType.isEmpty ? affinity.rawValue.uppercased() : declaredType.uppercased()
    }

    public var canDropInSQLite: Bool {
        !isGenerated && primaryKeyOrdinal == 0
    }
}

public struct SchemaIndex: Identifiable, Sendable, Hashable, Codable {
    public let id: String
    public let name: String
    public let columns: [String]
    public let isUnique: Bool
    public let origin: String
    public let isPartial: Bool
    public let sql: String?

    public init(name: String, columns: [String], isUnique: Bool, origin: String, isPartial: Bool, sql: String?) {
        self.id = name
        self.name = name
        self.columns = columns
        self.isUnique = isUnique
        self.origin = origin
        self.isPartial = isPartial
        self.sql = sql
    }
}

public struct SchemaTrigger: Identifiable, Sendable, Hashable, Codable {
    public let id: String
    public let name: String
    public let tableName: String
    public let sql: String

    public init(name: String, tableName: String, sql: String) {
        self.id = name
        self.name = name
        self.tableName = tableName
        self.sql = sql
    }
}

public enum SchemaConstraintKind: String, Sendable, Hashable, Codable {
    case primaryKey
    case foreignKey
    case unique
    case notNull
    case defaultValue
    case check
}

public struct SchemaConstraint: Identifiable, Sendable, Hashable, Codable {
    public let id: String
    public let kind: SchemaConstraintKind
    public let name: String?
    public let columns: [String]
    public let detail: String

    public init(id: String, kind: SchemaConstraintKind, name: String? = nil, columns: [String], detail: String) {
        self.id = id
        self.kind = kind
        self.name = name
        self.columns = columns
        self.detail = detail
    }
}

public struct GeneratedColumnInfo: Identifiable, Sendable, Hashable, Codable {
    public let id: String
    public let name: String
    public let declaredType: String
    public let storedKind: String

    public init(name: String, declaredType: String, storedKind: String) {
        self.id = name
        self.name = name
        self.declaredType = declaredType
        self.storedKind = storedKind
    }
}

public struct TableSummary: Identifiable, Sendable, Hashable {
    public let id: String
    public let name: String
    public let objectType: SQLiteObjectType
    public let isEditable: Bool
    public let columnCount: Int
    public let rowCount: Int?
    public let schemaName: String?
    public let objectName: String

    public init(
        name: String,
        objectType: SQLiteObjectType,
        isEditable: Bool,
        columnCount: Int,
        rowCount: Int? = nil,
        schemaName: String? = nil,
        objectName: String? = nil
    ) {
        self.id = name
        self.name = name
        self.objectType = objectType
        self.isEditable = isEditable
        self.columnCount = columnCount
        self.rowCount = rowCount
        self.schemaName = schemaName
        self.objectName = objectName ?? name
    }

}

public struct EditableTableDescriptor: Identifiable, Sendable, Hashable {
    public let id: String
    public let name: String
    public let objectType: SQLiteObjectType
    public let columns: [TableColumn]
    public let primaryKeyColumns: [String]
    public let rowIdentityStrategy: RowIdentityStrategy
    public let isWithoutRowID: Bool
    public let isEditable: Bool
    public let rowCount: Int?
    public let indexes: [SchemaIndex]
    public let triggers: [SchemaTrigger]
    public let constraints: [SchemaConstraint]
    public let generatedColumns: [GeneratedColumnInfo]
    public let schemaName: String?
    public let objectName: String
    /// Traditional inheritance can repeat this table's keys in descendants.
    public let hasInheritanceChildren: Bool

    public init(
        name: String,
        objectType: SQLiteObjectType,
        columns: [TableColumn],
        primaryKeyColumns: [String],
        rowIdentityStrategy: RowIdentityStrategy,
        isWithoutRowID: Bool,
        isEditable: Bool,
        rowCount: Int? = nil,
        indexes: [SchemaIndex] = [],
        triggers: [SchemaTrigger] = [],
        constraints: [SchemaConstraint] = [],
        generatedColumns: [GeneratedColumnInfo] = [],
        schemaName: String? = nil,
        objectName: String? = nil,
        hasInheritanceChildren: Bool = false
    ) {
        self.id = name
        self.name = name
        self.objectType = objectType
        self.columns = columns
        self.primaryKeyColumns = primaryKeyColumns
        self.rowIdentityStrategy = rowIdentityStrategy
        self.isWithoutRowID = isWithoutRowID
        self.isEditable = isEditable
        self.rowCount = rowCount
        self.indexes = indexes
        self.triggers = triggers
        self.constraints = constraints
        self.generatedColumns = generatedColumns
        self.schemaName = schemaName
        self.objectName = objectName ?? name
        self.hasInheritanceChildren = hasInheritanceChildren
    }

    public init(
        name: String,
        schemaName: String?,
        objectName: String?,
        objectType: SQLiteObjectType,
        columns: [TableColumn],
        primaryKeyColumns: [String],
        rowIdentityStrategy: RowIdentityStrategy,
        isWithoutRowID: Bool,
        isEditable: Bool,
        rowCount: Int? = nil,
        indexes: [SchemaIndex] = [],
        triggers: [SchemaTrigger] = [],
        constraints: [SchemaConstraint] = [],
        generatedColumns: [GeneratedColumnInfo] = [],
        hasInheritanceChildren: Bool = false
    ) {
        self.init(
            name: name,
            objectType: objectType,
            columns: columns,
            primaryKeyColumns: primaryKeyColumns,
            rowIdentityStrategy: rowIdentityStrategy,
            isWithoutRowID: isWithoutRowID,
            isEditable: isEditable,
            rowCount: rowCount,
            indexes: indexes,
            triggers: triggers,
            constraints: constraints,
            generatedColumns: generatedColumns,
            schemaName: schemaName,
            objectName: objectName,
            hasInheritanceChildren: hasInheritanceChildren
        )
    }

    public var summary: TableSummary {
        TableSummary(
            name: name,
            objectType: objectType,
            isEditable: isEditable,
            columnCount: columns.count,
            rowCount: rowCount,
            schemaName: schemaName,
            objectName: objectName
        )
    }

    public var searchableColumns: [TableColumn] {
        columns.filter { $0.affinity != .blob }
    }

    public var identityColumns: [TableColumn] {
        columns.filter(\.isIdentity)
    }

    public var fallbackSortColumns: [String] {
        switch rowIdentityStrategy {
        case .primaryKey:
            return primaryKeyColumns
        case .rowID:
            return ["_rowid_"]
        case .readOnly:
            return columns.map(\.name)
        }
    }

    public var qualifiedSQLIdentifier: String {
        if let schemaName {
            return qualifiedIdentifier(schema: schemaName, object: objectName)
        }
        return quoteIdentifier(name)
    }

    /// Key-based browsing and navigation address this physical table. Declarative
    /// partition roots retain their inclusive scope and tree-wide constraints.
    public var tableDataSQLSource: String {
        (schemaName != nil && objectType == .table && hasInheritanceChildren ? "ONLY " : "") + qualifiedSQLIdentifier
    }
}

/// Neutral descriptor spelling for both SQLite and PostgreSQL metadata.
public typealias TableDescriptor = EditableTableDescriptor

public enum PostgresTLSMode: String, Sendable, Hashable, Codable, CaseIterable, Identifiable {
    case disabled
    case required

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .disabled:
            return "TLS disabled"
        case .required:
            return "TLS required"
        }
    }
}

public struct PostgresConnectionConfiguration: Sendable, Hashable, Codable {
    public var host: String
    public var port: Int
    public var database: String
    public var username: String
    public var tlsMode: PostgresTLSMode

    public init(
        host: String,
        port: Int = 5432,
        database: String,
        username: String,
        tlsMode: PostgresTLSMode = .required
    ) {
        self.host = host.trimmingCharacters(in: .whitespacesAndNewlines)
        self.port = port
        self.database = database.trimmingCharacters(in: .whitespacesAndNewlines)
        self.username = username.trimmingCharacters(in: .whitespacesAndNewlines)
        self.tlsMode = tlsMode
    }

    public var canonicalIdentity: String {
        [
            host.lowercased(),
            String(port),
            database,
            username,
            tlsMode.rawValue,
        ].joined(separator: "\u{1F}")
    }

    public var stableStorageKey: String {
        SHA256.hash(data: Data(canonicalIdentity.utf8))
            .map { String(format: "%02x", $0) }
            .joined()
    }
}

public enum DatabaseTarget: Sendable, Hashable, Codable {
    case sqlite(URL)
    case postgres(PostgresConnectionConfiguration)

    private enum CodingKeys: String, CodingKey {
        case kind
        case url
        case configuration
    }

    private enum Kind: String, Codable {
        case sqlite
        case postgres
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        switch try container.decode(Kind.self, forKey: .kind) {
        case .sqlite:
            self = .sqlite(try container.decode(URL.self, forKey: .url).standardizedFileURL)
        case .postgres:
            self = .postgres(try container.decode(PostgresConnectionConfiguration.self, forKey: .configuration))
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .sqlite(let url):
            try container.encode(Kind.sqlite, forKey: .kind)
            try container.encode(url.standardizedFileURL, forKey: .url)
        case .postgres(let configuration):
            try container.encode(Kind.postgres, forKey: .kind)
            try container.encode(configuration, forKey: .configuration)
        }
    }

    public var identity: String {
        switch self {
        case .sqlite(let url):
            return "sqlite:" + url.standardizedFileURL.path
        case .postgres(let configuration):
            return "postgres:" + configuration.canonicalIdentity
        }
    }

    public var stableStorageKey: String {
        switch self {
        case .sqlite:
            return identity
        case .postgres(let configuration):
            return "postgres-" + configuration.stableStorageKey
        }
    }

    public var fileURL: URL? {
        if case .sqlite(let url) = self {
            return url.standardizedFileURL
        }
        return nil
    }

    public var displayName: String {
        switch self {
        case .sqlite(let url):
            return url.lastPathComponent
        case .postgres(let configuration):
            return "PostgreSQL · " + configuration.database
        }
    }

    public var isPostgres: Bool {
        if case .postgres = self { return true }
        return false
    }
}

/// A user-selected PostgreSQL document. It describes only the endpoint; the
/// app deliberately has no profile store or credential/login form.
public struct PostgresConnectionDocument: Sendable, Hashable, Codable {
    public static let supportedFileExtensions: Set<String> = [
        "postgres",
        "pgstudio",
    ]

    public var name: String?
    public var host: String
    public var port: Int
    public var database: String
    public var username: String
    public var tlsMode: PostgresTLSMode

    public init(
        name: String? = nil,
        host: String,
        port: Int = 5432,
        database: String,
        username: String,
        tlsMode: PostgresTLSMode = .required
    ) {
        self.name = name
        self.host = host
        self.port = port
        self.database = database
        self.username = username
        self.tlsMode = tlsMode
    }

    private enum CodingKeys: String, CodingKey {
        case name
        case host
        case port
        case database
        case username
        case tlsMode
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.name = try container.decodeIfPresent(String.self, forKey: .name)
        self.host = try container.decode(String.self, forKey: .host)
        self.port = try container.decodeIfPresent(Int.self, forKey: .port) ?? 5432
        self.database = try container.decode(String.self, forKey: .database)
        self.username = try container.decode(String.self, forKey: .username)
        self.tlsMode = try container.decodeIfPresent(PostgresTLSMode.self, forKey: .tlsMode) ?? .required
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(host, forKey: .host)
        try container.encode(port, forKey: .port)
        try container.encode(database, forKey: .database)
        try container.encode(username, forKey: .username)
        try container.encode(tlsMode, forKey: .tlsMode)
    }

    public var configuration: PostgresConnectionConfiguration {
        PostgresConnectionConfiguration(
            host: host,
            port: port,
            database: database,
            username: username,
            tlsMode: tlsMode
        )
    }

    public var displayName: String {
        let trimmedName = name?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        return trimmedName.isEmpty ? configuration.database : trimmedName
    }
}

public struct IdentityComponent: Sendable, Hashable {
    public let columnName: String
    public let value: SQLiteValue

    public init(columnName: String, value: SQLiteValue) {
        self.columnName = columnName
        self.value = value
    }
}

public enum TableRowIdentity: Sendable, Hashable {
    case primaryKey([IdentityComponent])
    case rowID(Int64)
}

/// Values shared by SQLite and PostgreSQL result/table surfaces. The original
/// SQLite cases remain source-compatible; PostgreSQL-only values are retained
/// losslessly instead of coercing them to an opaque display string.
public enum SQLiteValue: Sendable, Hashable {
    case null
    case integer(Int64)
    case double(Double)
    case boolean(Bool)
    case exactNumeric(String)
    case text(String)
    case uuid(String)
    case dateTime(String)
    case json(String)
    case array(String)
    case blob(Data)

    public static func binary(_ data: Data) -> Self {
        .blob(data)
    }

    public init(databaseValue: DatabaseValue) {
        switch databaseValue.storage {
        case .null:
            self = .null
        case .int64(let value):
            self = .integer(value)
        case .double(let value):
            self = .double(value)
        case .string(let value):
            self = .text(value)
        case .blob(let value):
            self = .blob(value)
        }
    }

    public var displayText: String {
        switch self {
        case .null:
            return "NULL"
        case .integer(let value):
            return String(value)
        case .double(let value):
            return value.formatted(.number.precision(.fractionLength(0...4)))
        case .boolean(let value):
            return value ? "TRUE" : "FALSE"
        case .exactNumeric(let value):
            return value
        case .text(let value):
            return value
        case .uuid(let value), .dateTime(let value), .json(let value), .array(let value):
            return value
        case .blob(let data):
            return "<\(data.count) bytes>"
        }
    }

    public var typeLabel: String {
        switch self {
        case .null:
            return "NULL"
        case .integer:
            return "INTEGER"
        case .double:
            return "REAL"
        case .boolean:
            return "BOOLEAN"
        case .exactNumeric:
            return "NUMERIC"
        case .text:
            return "TEXT"
        case .uuid:
            return "UUID"
        case .dateTime:
            return "DATE/TIME"
        case .json:
            return "JSON"
        case .array:
            return "ARRAY"
        case .blob:
            return "BLOB"
        }
    }

    public var editorText: String {
        switch self {
        case .null:
            return "NULL"
        case .integer(let value):
            return String(value)
        case .double(let value):
            return String(value)
        case .boolean(let value):
            return value ? "true" : "false"
        case .exactNumeric(let value):
            return value
        case .text(let value):
            return value
        case .uuid(let value), .dateTime(let value), .json(let value), .array(let value):
            return value
        case .blob:
            return ""
        }
    }

    public var databaseValue: DatabaseValue {
        switch self {
        case .null:
            return .null
        case .integer(let value):
            return value.databaseValue
        case .double(let value):
            return value.databaseValue
        case .boolean(let value):
            return value.databaseValue
        case .exactNumeric(let value):
            return value.databaseValue
        case .text(let value):
            return value.databaseValue
        case .uuid(let value), .dateTime(let value), .json(let value), .array(let value):
            return value.databaseValue
        case .blob(let value):
            return value.databaseValue
        }
    }
}

public typealias PostgresValue = SQLiteValue
public typealias DatabaseResultValue = SQLiteValue

public struct QueryResultColumn: Identifiable, Sendable, Hashable {
    public let id: Int
    public let name: String
    public let typeLabel: String

    public init(index: Int = 0, name: String, typeLabel: String) {
        self.id = index
        self.name = name
        self.typeLabel = typeLabel
    }
}

public struct QueryResultRow: Identifiable, Sendable, Hashable {
    public let id: Int
    public let values: [SQLiteValue]

    public init(id: Int, values: [SQLiteValue]) {
        self.id = id
        self.values = values
    }
}

public struct QueryResult: Sendable, Hashable {
    public let columns: [QueryResultColumn]
    public let rows: [QueryResultRow]
    public let isTruncated: Bool
    public let rowLimit: Int

    public init(columns: [QueryResultColumn], rows: [QueryResultRow], isTruncated: Bool, rowLimit: Int) {
        self.columns = columns.enumerated().map { QueryResultColumn(index: $0.offset, name: $0.element.name, typeLabel: $0.element.typeLabel) }
        self.rows = rows
        self.isTruncated = isTruncated
        self.rowLimit = rowLimit
    }

    public static let empty = QueryResult(columns: [], rows: [], isTruncated: false, rowLimit: 0)
}

public struct ExplainPlanRow: Identifiable, Sendable, Hashable {
    public let id: Int
    public let parent: Int
    public let notUsed: Int
    public let detail: String

    public init(id: Int, parent: Int, notUsed: Int, detail: String) {
        self.id = id
        self.parent = parent
        self.notUsed = notUsed
        self.detail = detail
    }
}

public struct QueryHistoryEntry: Identifiable, Sendable, Hashable, Codable {
    public let id: UUID
    public let title: String
    public let sqlText: String
    public let executedAt: Date
    public let durationMilliseconds: Double
    public let rowCount: Int
    public let succeeded: Bool
    public let message: String?

    public init(
        id: UUID = UUID(),
        title: String,
        sqlText: String,
        executedAt: Date = Date(),
        durationMilliseconds: Double,
        rowCount: Int,
        succeeded: Bool,
        message: String? = nil
    ) {
        self.id = id
        self.title = title
        self.sqlText = sqlText
        self.executedAt = executedAt
        self.durationMilliseconds = durationMilliseconds
        self.rowCount = rowCount
        self.succeeded = succeeded
        self.message = message
    }
}

public enum DataTransferFormat: String, CaseIterable, Identifiable, Sendable, Hashable {
    case csv
    case json

    public var id: String { rawValue }

    public var fileExtension: String {
        switch self {
        case .csv: return "csv"
        case .json: return "json"
        }
    }
}

public struct ImportRowsResult: Sendable, Hashable {
    public let insertedRowCount: Int
    public let skippedRowCount: Int
    public let messages: [String]

    public init(insertedRowCount: Int, skippedRowCount: Int, messages: [String] = []) {
        self.insertedRowCount = insertedRowCount
        self.skippedRowCount = skippedRowCount
        self.messages = messages
    }
}

public struct TableColumnDraft: Identifiable, Sendable, Hashable {
    public let id: UUID
    public var name: String
    public var type: String
    public var isPrimaryKey: Bool
    public var isNotNull: Bool
    public var defaultValueSQL: String

    public init(
        id: UUID = UUID(),
        name: String = "",
        type: String = "TEXT",
        isPrimaryKey: Bool = false,
        isNotNull: Bool = false,
        defaultValueSQL: String = ""
    ) {
        self.id = id
        self.name = name
        self.type = type
        self.isPrimaryKey = isPrimaryKey
        self.isNotNull = isNotNull
        self.defaultValueSQL = defaultValueSQL
    }
}

public struct TableCreateDraft: Sendable, Hashable {
    public var tableName: String
    public var columns: [TableColumnDraft]

    public init(tableName: String = "", columns: [TableColumnDraft] = [TableColumnDraft(name: "id", type: "INTEGER", isPrimaryKey: true)]) {
        self.tableName = tableName
        self.columns = columns
    }
}

public struct TableRow: Sendable, Hashable {
    public let identity: TableRowIdentity
    public let values: [SQLiteValue]

    public init(identity: TableRowIdentity, values: [SQLiteValue]) {
        self.identity = identity
        self.values = values
    }
}

public enum TableCountState: Sendable, Hashable {
    case unknown
    case atLeast(Int)
    case exact(Int)

    public var navigationCount: Int {
        switch self {
        case .unknown: return 0
        case .atLeast(let count): return count + 1
        case .exact(let count): return count
        }
    }
    public var label: String {
        switch self {
        case .unknown: return "Count unknown"
        case .atLeast(let count): return "At least \(count.formatted()) rows"
        case .exact(let count): return "\(count.formatted()) rows (last count)"
        }
    }
}

public struct TablePageCursor: Sendable, Hashable {
    public let values: [String: DatabaseResultValue]
    public init(values: [String: DatabaseResultValue]) { self.values = values }
}

extension TableDescriptor {
    /// Nullable unique constraints and partial/expression indexes cannot locate every row.
    public var paginationKeyColumns: [String] {
        guard objectType == .table || objectType == .partitionedTable else { return [] }
        if rowIdentityStrategy == .rowID { return ["_rowid_"] }
        let required = Set(columns.filter(\.notNull).map(\.name))
        if !primaryKeyColumns.isEmpty,
           Set(primaryKeyColumns).isSubset(of: required) || (schemaName == nil && !isWithoutRowID && primaryKeyColumns.count == 1 && columns.first(where: { $0.name == primaryKeyColumns[0] })?.declaredType.uppercased() == "INTEGER") {
            return primaryKeyColumns
        }
        return indexes.first { $0.isUnique && !$0.isPartial && !$0.columns.isEmpty && Set($0.columns).isSubset(of: required) }?.columns ?? []
    }

    public var pagingDescription: String {
        let scope = hasInheritanceChildren ? "This table's own rows; open descendant tables separately. " : ""
        return scope + (paginationKeyColumns.isEmpty
            ? "Offset pages: no unique key. Concurrent changes can move or repeat rows; use a snapshot export for a consistent result."
            : "Key-based next pages. Pages read live data; changes to sort or key values can move rows. Export all matching rows for one consistent snapshot.")
    }
}

public struct TableChunk: Sendable, Hashable {
    public let rows: [TableRow]
    public let totalRowCount: Int
    public let hasMore: Bool
    public let countState: TableCountState
    public let offset: Int
    public let limit: Int

    public init(rows: [TableRow], totalRowCount: Int, offset: Int, limit: Int, countState: TableCountState? = nil, hasMore: Bool? = nil) {
        self.rows = rows
        self.totalRowCount = totalRowCount
        self.hasMore = hasMore ?? (offset + rows.count < totalRowCount)
        self.countState = countState ?? .exact(totalRowCount)
        self.offset = offset
        self.limit = limit
    }

    public static func empty(limit: Int) -> TableChunk {
        TableChunk(rows: [], totalRowCount: 0, offset: 0, limit: limit)
    }

    public var rowRange: Range<Int> {
        offset..<(offset + rows.count)
    }

    public func contains(absoluteRow row: Int) -> Bool {
        rowRange.contains(row)
    }
}

public struct SortState: Sendable, Hashable {
    public let columnName: String
    public let direction: SortDirection

    public init(columnName: String, direction: SortDirection) {
        self.columnName = columnName
        self.direction = direction
    }
}

public enum ColumnFilterComparison: String, CaseIterable, Identifiable, Sendable, Hashable {
    case contains, equal, notEqual, lessThan, lessThanOrEqual, greaterThan, greaterThanOrEqual, between, isNull, isNotNull
    public var id: String { rawValue }
    public var label: String {
        switch self {
        case .contains: return "Text contains"
        case .equal: return "Equals"
        case .notEqual: return "Does not equal"
        case .lessThan: return "Less than"
        case .lessThanOrEqual: return "At most"
        case .greaterThan: return "Greater than"
        case .greaterThanOrEqual: return "At least"
        case .between: return "Between (inclusive)"
        case .isNull: return "Is NULL"
        case .isNotNull: return "Is not NULL"
        }
    }
    public var requiresValue: Bool { self != .isNull && self != .isNotNull }
}

public struct ColumnFilter: Sendable, Hashable {
    public let columnName: String
    public let value: String

    public let comparison: ColumnFilterComparison
    public let upperValue: String?

    public init(columnName: String, value: String = "", comparison: ColumnFilterComparison = .contains, upperValue: String? = nil) {
        self.columnName = columnName
        self.value = value
        self.comparison = comparison
        self.upperValue = upperValue
    }
}

public struct TableQueryState: Sendable, Hashable {
    public var after: TablePageCursor? = nil
    public var requestExactCount = false
    public var cachedExactCount: Int? = nil
    public var searchText: String
    public var columnFilters: [ColumnFilter]
    public var sort: SortState?
    public var offset: Int
    public var limit: Int

    public init(
        searchText: String = "",
        columnFilters: [ColumnFilter] = [],
        sort: SortState? = nil,
        offset: Int = 0,
        limit: Int = 300
    ) {
        self.searchText = searchText
        self.columnFilters = columnFilters
        self.sort = sort
        self.offset = offset
        self.limit = limit
    }

    public var sanitizedSearchText: String {
        searchText.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    public var sanitizedFilters: [ColumnFilter] {
        columnFilters
            .filter { $0.comparison != .contains || !$0.value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
            .sorted { $0.columnName.localizedStandardCompare($1.columnName) == .orderedAscending }
    }
}

public struct CellEditChange: Sendable, Hashable {
    public let descriptor: EditableTableDescriptor
    public let rowIdentity: TableRowIdentity
    public let columnName: String
    public let rawValue: String

    public init(
        descriptor: EditableTableDescriptor,
        rowIdentity: TableRowIdentity,
        columnName: String,
        rawValue: String
    ) {
        self.descriptor = descriptor
        self.rowIdentity = rowIdentity
        self.columnName = columnName
        self.rawValue = rawValue
    }
}

public struct SQLiteUserError: Error, Sendable, Hashable, Identifiable, LocalizedError {
    public enum Kind: String, Sendable, Hashable {
        case busy
        case constraint
        case readOnly
        case invalidInput
        case notFound
        case authentication
        case network
        case permission
        case timeout
        case syntax
        case missingCredential
        case generic
    }

    public let kind: Kind
    public let message: String
    public let recoverySuggestion: String?

    public init(kind: Kind, message: String, recoverySuggestion: String? = nil) {
        self.kind = kind
        self.message = message
        self.recoverySuggestion = recoverySuggestion
    }

    public var id: String {
        "\(kind.rawValue):\(message)"
    }

    public var errorDescription: String? {
        message
    }

    public static func from(_ error: any Error) -> SQLiteUserError {
        if let userError = error as? SQLiteUserError {
            return userError
        }

        if let dbError = error as? DatabaseError {
            let message = dbError.message ?? dbError.resultCode.description
            switch dbError.resultCode {
            case .SQLITE_BUSY:
                return SQLiteUserError(
                    kind: .busy,
                    message: message,
                    recoverySuggestion: "The database is busy. Retry the change after pending work finishes."
                )
            case .SQLITE_CONSTRAINT:
                return SQLiteUserError(kind: .constraint, message: message)
            case .SQLITE_READONLY:
                return SQLiteUserError(kind: .readOnly, message: message)
            default:
                return SQLiteUserError(kind: .generic, message: message)
            }
        }

        return SQLiteUserError(kind: .generic, message: error.localizedDescription)
    }
}

public typealias DatabaseUserError = SQLiteUserError

public func quoteIdentifier(_ value: String) -> String {
    "\"\(value.replacingOccurrences(of: "\"", with: "\"\""))\""
}

public func qualifiedIdentifier(schema: String, object: String) -> String {
    "\(quoteIdentifier(schema)).\(quoteIdentifier(object))"
}

func quoteStringLiteral(_ value: String) -> String {
    "'\(value.replacingOccurrences(of: "'", with: "''"))'"
}

func parseSQLiteValue(_ rawValue: String, for column: TableColumn, recognizesNullLiteral: Bool = true) throws -> SQLiteValue {
    let trimmed = rawValue.trimmingCharacters(in: .whitespacesAndNewlines)
    if recognizesNullLiteral && trimmed.uppercased() == "NULL" {
        if column.notNull {
            throw SQLiteUserError(kind: .invalidInput, message: "\(column.name) does not allow NULL values.")
        }
        return .null
    }

    switch column.affinity {
    case .integer:
        if let intValue = Int64(trimmed) {
            return .integer(intValue)
        }
        return .text(rawValue)
    case .real:
        if let doubleValue = Double(trimmed) {
            return .double(doubleValue)
        }
        return .text(rawValue)
    case .blob:
        throw SQLiteUserError(kind: .invalidInput, message: "Inline blob editing is not supported for \(column.name).")
    case .numeric:
        if let intValue = Int64(trimmed) {
            return .integer(intValue)
        }
        if let doubleValue = Double(trimmed) {
            return .double(doubleValue)
        }
        return .text(rawValue)
    case .text, .none:
        return .text(rawValue)
    }
}

extension TableCountState {
    static func forPage(query: TableQueryState, rowCount: Int, hasMore: Bool, exactCount: Int?) -> Self {
        let end = query.offset + rowCount
        if query.after != nil { return exactCount.map(Self.exact) ?? .unknown }
        if let exactCount, exactCount >= end + (hasMore ? 1 : 0) { return .exact(exactCount) }
        if hasMore { return .atLeast(end) }
        return rowCount > 0 || query.offset == 0 ? .exact(end) : .unknown
    }
}
